#!/usr/bin/env php
<?php

require 'hashbang.php';

$app = new HashBang(function($firstname, $lastname, $options) {
    $output = "Hello, {$firstname}";
    if ($lastname) {
        $output .= " {$lastname}";
    }
    $output .= "!\n";

    if ($options['yell']) {
        $output = strtoupper($output);
    }

    echo $output;
});

$app->addArg('firstname');
$app->addArg('lastname', false);

$app->addSwitch('-y', '--yell');

$app->go();
